### ISSUE TITLE
Does not work with IISExpress

### ISSUE THREAD

**Issue by rjperes** [aspnet/NodeServices#2]
Doesn't work with *IISExpress*, only *web*:

SocketException: An existing connection was forcibly closed by the remote host.

IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host.
System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)

WebException: The underlying connection was closed: An unexpected error occurred on a receive.
System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)

HttpRequestException: An error occurred while sending the request.
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

**Comment by SteveSandersonMS** [comment]
It did work in IISExpress a week or two ago (we made it work at the MVP summit hackathon). Looks like one of the dependencies has changed. I'll look into it.

**Comment by SteveSandersonMS** [comment]
After updating everything to ASP.NET 5 RC1, it's working fine with IIS Express as far as I can tell. If you still get any issues after fetching the latest version of this repo and running it with ASP.NET 5 RC1 installed, please let me know.

**Comment by rjperes** [comment]
Yeah, it seems to be working now... thanks!

**Comment by gregbty** [comment]
I am now having this issue as well. I have ASP.NET 5 RC1 Update 1 installed. It happens with IISExpress and web.
