### ISSUE TITLE
Custom JsonSerializerSettings

### ISSUE THREAD

**Issue by gregbty** [aspnet/NodeServices#27]
Currently all the OutOfProcessNodeInstance classes use a JsonSerializerSettings object that is created inline. Can it be switched to pull from the JsonOutputFormatter that is created during the startup of the application? It is available via the asp.net DI.

**Comment by gregbty** [comment]
Here is the workaround I am using: https://github.com/gregbty/NodeServices/commit/0293ac6d622198782737754e46b96ccaef0bcb23

**Comment by SteveSandersonMS** [comment]
Could you describe what use case this would help with? I would have thought that the interprocess communication format was an internal implementation detail, and exposing it to variations in JsonSerializerSettings would open a risk of very hard-to-diagnose inconsistencies and faults.

**Comment by gregbty** [comment]
I think when I originally reported this issue it was due to how the initial payload was being sent into the Node process. I will revert and do some testing. If I find a valid case I will update this, if not I will close it.

**Comment by gregbty** [comment]
Can cut an alpha7 release to Nuget? Alpha6 still uses a different IServiceCollection abstraction.

**Comment by SteveSandersonMS** [comment]
The updated builds are all on nuget with version `1.0.0-beta-000001`. The `00000` prefix is because NuGet doesn't yet support dot-separated prerelease suffixes.
