### ISSUE TITLE
NodeServices Publised Nuget Pkg is Out Of Date

### ISSUE THREAD

**Issue by QuinntyneBrown** [aspnet/NodeServices#29]
The NodeServices version used in the same in the Music Store Sample is alpha7. The package available on Nuget is alpha6

**Comment by SteveSandersonMS** [comment]
Thanks for the pointer - this is now published.

**Comment by CoskunSunali** [comment]
To which nuget feed are you exactly publishing the packages?

I cannot seem to find it on aspnetcidev :/

**Comment by CoskunSunali** [comment]
Sorry, not aspnetcidev but https://www.nuget.org/packages/Microsoft.AspNet.NodeServices.
