### ISSUE TITLE
NodeServices not compatible with ASPNET rc-1

### ISSUE THREAD

**Issue by QuinntyneBrown** [aspnet/NodeServices#30]
I have attempted to use NodeServices alpha6 with ASPNET rc-1.

https://github.com/QuinntyneBrown/js-design-patterns-getting-started

I get dependency issues. NodeServices alpha6 is not compatible with ASPNET rc-1.

**Comment by davidfowl** [comment]
Isn't there an alpha7

**Comment by QuinntyneBrown** [comment]
Not publicly available. https://www.nuget.org/packages/Microsoft.AspNet.NodeServices

**Comment by QuinntyneBrown** [comment]
So, how do I get 7 without stealing it from the sample app, which I rather not do :)

**Comment by QuinntyneBrown** [comment]
Tried to run my solution by referencing the NodeServices project which gave me alpha7. I received the following errors. I think there maybe an issue there. I will keep experiementing.

![image](https://cloud.githubusercontent.com/assets/1749159/12136797/343e3fda-b419-11e5-9aa9-86db56b27a43.png)

**Comment by SteveSandersonMS** [comment]
I've pushed the alpha7 packages. It should all work on RC1 now (in fact, it depends on RC1), but please let me know if not.

**Comment by ellern** [comment]
Did you forget to push Microsoft.AspNet.NodeServices 1.0.0-alpha7 to nuget? I got the following error when I added Microsoft.AspNet.AngularServices 1.0.0-alpha7 to my project:

`Unable to locate Dependency Microsoft.AspNet.NodeServices >= 1.0.0-alpha7`

**Comment by josiah1888** [comment]
@SteveSandersonMS I also have the 
`Unable to locate Dependency Microsoft.AspNet.NodeServices >= 1.0.0-alpha7` 
error on my project. 

Checking https://www.nuget.org/packages/Microsoft.AspNet.AngularServices
>Microsoft.AspNet.NodeServices (>= 1.0.0-alpha7)

Checking https://www.nuget.org/packages/Microsoft.AspNet.NodeServices
>Microsoft.AspNet... 1.0.0-alpha6 (this version)	177	Thursday, November 5, 2015

Check again if you've pushed Microsoft.AspNet.NodeServices 1.0.0-alpha7 to nuget for me?

**Comment by SebastianStehle** [comment]
i would like to see it as well.

**Comment by parmarnishant** [comment]
is this resolved ?

**Comment by josiah1888** [comment]
@parmarnishant A quick check of https://www.nuget.org/packages/Microsoft.AspNet.NodeServices says no, the nuget package still needs to be updated
