### ISSUE TITLE
Update to use Babel 6

### ISSUE THREAD

**Issue by xabikos** [aspnet/NodeServices#31]
This is an awesome project and I founded recently. I am very interested especially for React and server side rendering part of it. I am trying to improve the tooling on the field so I have published a [nuget package](https://www.nuget.org/packages/Webpack/) [GitHub project](https://github.com/xabikos/aspnet-webpack) which simplifies the webpack integration. Especially for simple scenarios like the sample an external configuration file is not required and all the references to the scripts are added automatically. I tried to add it to the sample and make a pull request but when update the babel to latest versions (6+) I am getting an error for server side rendering. Are there any plans to update to the latest babel?

**Comment by SteveSandersonMS** [comment]
Yes, absolutely! I'll take a look at your pull request shortly. Thanks for your contribution!
