### ISSUE TITLE
Is it working with angular 2.0.0-beta.1?

### ISSUE THREAD

**Issue by ellern** [aspnet/NodeServices#33]
I've tried updating the MusicStore sample to use angular 2.0.0-beta.1, but couldn't get it to work.

Has anybody had success using it with angular 2.0.0-beta.1?

**Comment by michalstepien** [comment]
+1

**Comment by SteveSandersonMS** [comment]
Yes, I just pushed an update. It's all on angular 2.0.0-beta.1 now.
