### ISSUE TITLE
SocketException: An existing connection was forcibly closed by the remote host

### ISSUE THREAD

**Issue by ellern** [aspnet/NodeServices#34]
I can't figure out why I'm getting this exception when trying this with my app. Any hints?

<img width="718" alt="screen shot 2016-02-01 at 19 21 30" src="https://cloud.githubusercontent.com/assets/4930511/12726747/8aec2558-c919-11e5-8b1d-f74c69f75d88.png">

**Comment by CedricDumont** [comment]
I had the same issue when testing the samples. (https://github.com/aspnet/NodeServices/issues/44) It was my first attempt and it worked when installing and testing from the command line. (*dnx web*)

Then, when opening the solution from viusal studio (...\NodeServices\samples\react\MusicStore\MusicStore.xproj) and starting the project with IISExpress, I had a page telling me to install the module (aspnet-webpack-react).
I installed it and had the same page displayed (as you mention). Then when launching again from the command line, I had the same error... but with these added info:

```
[Node]
[Node] C:\projects\cloned\NodeServices\samples\react\MusicStore\node_modules\memory-fs\lib\MemoryFileSystem.js:114
[Node]                  throw new MemoryFileSystemError(errors.code.ENOENT, _path);
[Node]                  ^
[Node] Error: no such file or directory
[Node]     at MemoryFileSystem.readFileSync (C:\projects\cloned\NodeServices\samples\react\MusicStore\node_modules\memory-fs\lib\MemoryFileSystem.js:1
14:10)
[Node]     at C:\projects\cloned\NodeServices\samples\react\MusicStore\node_modules\aspnet-webpack\LoadViaWebpack.js:68:61
[Node]     at Compiler.<anonymous> (C:\projects\cloned\NodeServices\samples\react\MusicStore\node_modules\webpack\lib\Compiler.js:194:14)
[Node]     at Compiler.emitRecords (C:\projects\cloned\NodeServices\samples\react\MusicStore\node_modules\webpack\lib\Compiler.js:282:37)
[Node]     at Compiler.<anonymous> (C:\projects\cloned\NodeServices\samples\react\MusicStore\node_modules\webpack\lib\Compiler.js:187:11)
[Node]     at C:\projects\cloned\NodeServices\samples\react\MusicStore\node_modules\webpack\lib\Compiler.js:275:11
[Node]     at Compiler.applyPluginsAsync (C:\projects\cloned\NodeServices\samples\react\MusicStore\node_modules\tapable\lib\Tapable.js:60:69)
[Node]     at Compiler.afterEmit (C:\projects\cloned\NodeServices\samples\react\MusicStore\node_modules\webpack\lib\Compiler.js:272:8)
[Node]     at Compiler.<anonymous> (C:\projects\cloned\NodeServices\samples\react\MusicStore\node_modules\webpack\lib\Compiler.js:267:14)
[Node]     at C:\projects\cloned\NodeServices\samples\react\MusicStore\node_modules\async\lib\async.js:52:16
fail: Microsoft.AspNet.Diagnostics.ExceptionHandlerMiddleware[0]
      An unhandled exception has occurred: An error occurred while sending the request.
```

I then deleted all my node_modules and performed a reintsall without that package. *aspnet-webpack-react*) and retested with visual studio.

On first run I had the following exception:

```
Call to Node module failed with error: To use ReactHotModuleReplacement, you must install the NPM package 'aspnet-webpack-react'."}
```

I disabled the hotreload in the startup.cs class, but nothing helped... now I can't even restart the sample with the command line. so I think it has nothing to do with *aspnet-webpack-react*

I hope with these added information, the team could solve this problem. I would like to use asp.net core to create a React universal app (with prerendering on the server) and for now had lot's of issue, but it's still in 'aplha' so... will wait some more time

**Comment by SteveSandersonMS** [comment]
Sorry it's been a while, but so much has changed since this was posted (ASP.NET Core has updated to RC2, all the NodeServices-related packages have updated dramatically to match), that it's probably not useful to try to diagnose this. I'm not aware of this being an outstanding issue in current versions of the technology.

Can I suggest you try with the new bits?

 * Install ASP.NET Core RC2
 * Install the Yeoman generator (`npm install -g yo generator-aspnetcore-spa`)
 * Make a new project (`yo aspnetcore-spa`)
 * Run (`dotnet run`)

This should get you going with the latest packages!
