### ISSUE TITLE
Support in-process V8 engine, via VroomJs

### ISSUE THREAD

**Issue by pauldotknopf** [aspnet/NodeServices#36]
https://github.com/pauldotknopf/vroomjs-core

I have started porting VroomJs to .NET Core. It works with CLR currently. .NET Core requires some more ```#if def``` work. It should be done soon though.

I think this library should be implemented as a new hosting model.

Are there currently any plans to support an embedded v8 engine?

**Comment by pauldotknopf** [comment]
Before I answer your questions, I want to give some clarity on the direction I am going with this V8 engine.

---------------------------------------------------------

https://github.com/pauldotknopf/javascriptviewengine

You initialize the V8 engine...

```c#
public class JsEngineInitializer : IJsEngineInitializer
{
    public void Initialize(IJsEngine engine)
    {
        engine.Execute(@"
            var RenderView = function(path, model) {
                return ""<html><head></head><body><strong>"" + model.Greeting + ""</strong ></body>"";
            };

            var RenderPartialView = function(path, model) {
                return ""<div><strong>"" + model.Greeting + ""</strong></div>"";
            };
        ");
    }
}
```

And you you MVC as you traditionly would, with a minor caviet. Your view name must begin with ```js-```.

```c#
public class HomeController : Controller
{
    public IActionResult Index(string greeting = "Hello word!")
    {
        return View("js-Index", new GreetingViewModel { Greeting = greeting });
    }
}
```

No razor, pure js rendering.

---------------------------------------------------------

> Your intent is to support cross-platform CoreCLR, right? I just got it to build on Mono for OS X but I can see that, as per your comment, it doesn't currently work on CoreCLR.

You are correct. There are a lot of usages of ```System.Timers``` (and others) that needs to be changed to a cross-platform API.

> How would this differ in functionality from running code in a Node environment?

You are correct in that the V8 environment is not a traditional node environment. However, webpack solves this issue. Take a look at that [gulpfile](https://github.com/pauldotknopf/react-dot-net/blob/master/src/React/gulpfile.js) for the React demo I created. Notice that is uses webpack to build both the client, AND server script. This gives you multiple things.

1. ```require('../img.png')``` works in react/knockout rendering. It doesn't work on nodejs without some hacking with [webpack-isomorphic-tools](https://github.com/halt-hammerzeit/webpack-isomorphic-tools). Also, this works with using ```require('../App.scss').brand``` for strongly-typed css classes.
2. 100% universal rendering. The current NodeServices approach is more of a "donut-whole rendering" approach to server side rendering. It is great for initial load time, but when navigating to other pages, you have to make a full request that goes through mvc/razor, and then eventually server-renders some react stuff. My approach allows you to navigate to any page on the client side, while doing an f5 refresh will give you a complete server rendered copy of the same exact content.

> I have been waiting for Edge.js to gain support for hosting Node in-process on CoreCLR but am not sure if/when that feature will ship.

I like the idea of webpacking the server script so that webpack loaders can be used for server rendering content. However, I like the idea of also using node to give people complete control over the rendering, instead of relying on webpack to use loaders for everything. However, I haven't run into any limitation with regards to rendering only. Server-side rendering scripts typically don't need access to the file system or os (which node provides). However, I think the overhead of using [webpack-isomorphic-tools](https://github.com/halt-hammerzeit/webpack-isomorphic-tools) would be worth it if we can get Edge.js (or something similar) working 100% in an embedded environment.

> Is performance the key benefit of using in-process hosting with VroomJS, or is there anything else? If it's mainly about perf, do you have any sense of just how much faster it is?

Performance is the key factor. However, when it is in process, you can do things like forwarding ```console.log('message');``` commands to the .NET ```Console.WriteLine("console.log(" + message + ")");``` I don't have any sense of how much faster it actually is though.

**Comment by xabikos** [comment]
Sorry to interfere but I am really glad to hear you keep in eye on Edge.js as I believe this is the best solution for this concept. I have a long experience with Reactjs.NET which is a fantastic library and gives an option to use VroomJs but has some limitations. As Steve mentioned the option to use whatever npm package in the script is amazing. 

Let's hope that the support for CoreCLR in Edge.js will be available soon.

**Comment by pauldotknopf** [comment]
@xabikos May I ask you how you handle client/server side routing? Are all links a traditional redirect, or are you using react-router to do client-side routing to separate pages?

**Comment by xabikos** [comment]
@pauldotknopf you mean client/server side routing with Reactjs.NET?

**Comment by pauldotknopf** [comment]
Yes. Completely client-side routing, with an F5 giving you a complete refresh of the same exact page.

**Comment by pauldotknopf** [comment]
It looks like React.NET doesn't currently have an answer for it.

https://github.com/reactjs/React.NET/issues/64

**Comment by xabikos** [comment]
Yes I know what you mean and luckily we didn't have to support this scenario as the application is kinda exceptional. We are using the Reactjs.NET with webforms and from the server side perspective we are always returning the same webform that contains an empty div where the React content is added. Then based on the route we just passing a different json model to the server side routing and in this way we can produce a different page. But keep in mind that there is no need to have React client side after the server side rendering. I am not sure if I made myself clear.

But in any case we haven't find a way to support the full scenario and go full isomorphic with routing on the server with React.NET.

**Comment by pauldotknopf** [comment]
> We are using the Reactjs.NET with webforms and from the server side perspective we are always returning the same webform that contains an empty div where the React content is added.

So you aren't doing any server-side rendering? If so, what does React.NET give you?

> But keep in mind that there is no need to have React client side after the server side rendering. I am not sure if I made myself clear.

Ah, so your using is strictly as a template engine? Why not use razor? You don't have to use razor within the context of MVC (so it can be used in webforms).

For what it is worth, here is a React and .NET example that has the client-server routing scenario handled.
https://github.com/pauldotknopf/react-dot-net

**Comment by xabikos** [comment]
Yes we are using the React.NET as template engine. To give some more context the application gives the admin to create custom webpages by adding some predefined html widgets through a GUI. Let's say the user has a basic layout and the on the main content need to add a google map content. Then we use React to reflect this change immediately on client side and when the user saves we just save a big json object that represent the widget and the configuration. When somebody tries to access that page then we give this json object to React.NET and we get the same page but render on the server side this time. I hope is a bit more clear now.

**Comment by pauldotknopf** [comment]
Ah, clear now. Actually pretty cool!

**Comment by xabikos** [comment]
Yes I was also amazed when we saw this in action as we managed to merge Reactjs and React.NET with such an old technology as Webforms

**Comment by SteveSandersonMS** [comment]
> This was a big problem I had with both NodeServices and Reactjs.NET. It didn't actually solve the routing issue. It is more of a donut-hole render of reactjs content which must be server up via a tradtional HTTP GET web request.

Can you clarify what problem you're getting at? I'm not familiar with the donut-hole analogy or in what other way you'd want to serve your page besides responding to HTTP GET requests.

> Yes. Completely client-side routing, with an F5 giving you a complete refresh of the same exact page.

Again, I'm not sure what difference you're hinting at. With the NodeServices-based templates, hitting F5 *does* bring you back to the same page. As in, we do correctly pass through the requested URL into the Angular/React/etc router.

Apologies if I'm missing something obvious, but if something's missing in handling of routing, could you give repro steps and say what you would want to happen (and what happens instead)?

Thanks!

**Comment by Kukkimonsuta** [comment]
I think he's hinting at rendering only part of the page using `React` or other js library instead of the whole page including `html` and so on. In most cases this comes in play only for things like `title` or `meta` tags and the usual solution is to export such information from the server renderer and update the tags of the accordingly.

I believe the best would be if the hosting model was pluggable, so there could be packages like `NodeServices.Node`, `NodeServices.VroomJs` or `NodeServices.EdgeJs` and let the end user decide which fits the best.

**Comment by pauldotknopf** [comment]
Sorry for the delay.

> Can you clarify what problem you're getting at? I'm not familiar with the donut-hole analogy or in what other way you'd want to serve your page besides responding to HTTP GET requests.

The previous reply nailed it. You aren't rendering the meta tags. This makes it impossible to have client-side routing that manages the title/meta tags as well.

Also, what is the plan to handle individual server routes to fetch data to pre-render, specific to that page?

**Comment by joshburgess** [comment]
I agree with @Kukkimonsuta  and @pauldotknopf about wanting better support for server-side rendering. I'd also like to have the option to avoid using Razor for server-side rendering (the asp-prerender-module and asp-prerender-webpack-config tags). I would prefer to just configure these things in the controller and render without Razor altogether.

**Comment by SteveSandersonMS** [comment]
OK, thanks for clarifying.

> You aren't rendering the meta tags.
You can render as much of the page with your JS code as you want - your Razor page can be nothing but an invocation of your Angular/React app if desired. I appreciate that the samples don't demonstrate this.

> I'd also like to have the option to avoid using Razor for server-side rendering
OK, understood. This is already possible, in the sense that you can directly invoke `Microsoft.AspNetCore.SpaServices.Prerendering.Prerenderer.RenderToString`, though the API isn't exactly optimised for ease of use, and it would be nicer to have an `IActionResult` that does this so the controller code is more testable. I'll look into adding an action result for this.

> Also, what is the plan to handle individual server routes to fetch data to pre-render, specific to that page?
The templates demonstrate ways of fetching data, and in the case of `Angular2Spa` and `ReactReduxSpa` which do server-side rendering, the data is being fetched and prerendered on the server. Could you clarify what additional feature you're looking for, or is this what you need?

**Comment by SteveSandersonMS** [comment]
I'll close this now as the discussion seems to have concluded, and the original suggestion (support in-process JS engine) is reasonably covered by the existing issue #5. I don't think we're heading towards using a standalone V8 engine (as opposed to Node) because of the immense benefits of using Node and having its wide ecosystem all working perfectly.
