### ISSUE TITLE
Support Web Workers for Angular2

### ISSUE THREAD

**Issue by jimitndiaye** [aspnet/NodeServices#37]
There doesn't seem to be any obvious way of configuring a pre-rendered angular2 app that uses one or more web workers. It'd be great if the music store was updated to demonstrate this functionality as illustrated in this [Angular2 universal starter kit](https://github.com/alexpods/angular2-universal-starter).

**Comment by jimitndiaye** [comment]
Also looking at the source of ```angular-rendering.js``` there doesn't seem to be support for using preboot, i.e ```renderToStringWithPreboot``` rather than ```renderToString```.

**Comment by SteveSandersonMS** [comment]
That's correct - thanks for bringing up these points.

If you have any time to work on adding this functionality I'd be pleased to take a pull request. Otherwise I'll aim to get to it at some point, though there are lots of other jobs higher up on my list so there's no ETA.

**Comment by jimitndiaye** [comment]
I'll take a stab at adding preboot support. That should be relatively straight forward. Workers might be slightly trickier but I have some ideas.

**Comment by jimitndiaye** [comment]
I've got preboot mostly working. However I notice that in the angular2spa template you're requiring the client code to do the server side render. If that's the model you're going for then it makes more sense for the other of the client code to be responsible. That way AngularServices doesn't have to be changed every time angular2 changes.

In any case I changed renderToString as follows:
```javascript
    renderToString: function(callback, options) {
        try {
            var component = findAngularComponent(options);
            var serverBindings = [
                ngRouter.ROUTER_BINDINGS,
                ngUniversal.HTTP_PROVIDERS,
                // TODO: BASE_URL has been replaced by REQUEST_URL in angular2@2.0.0-beta.7
                ngCore.provide(ngUniversal.BASE_URL, { useValue: options.requestUrl }), 
                ngCore.provide(ngRouter.APP_BASE_HREF, { useValue: '/' }),
                ngUniversal.SERVER_LOCATION_PROVIDERS
            ];

            return (options.preboot
                ? ngUniversalRender.renderToStringWithPreboot(component, serverBindings, {
                   freeze: { name: 'spinner' },
                    replay: 'rerender',
                    buffer: true,
                    debug: true,
                    uglify: false,
                })
                : ngUniversalRender.renderToString(component, serverBindings)).then(
                function(successValue) { callback(null, successValue); },
                function(errorValue) { callback(errorValue); }
            );
        } catch (synchronousException) {
            callback(synchronousException);
        }
    }
```
As you can see not much needs to change to support preboot. In your Angular2Spa template, for instance, just call ```ngUniversalRender.renderToStringWithPreboot``` as illustrated above.

Incidentally you may obviate the need for specific Angular2Services and ReactServices by just putting the common functionality in SpaServices. Even React could use cache priming so no need to keep it for Angular2Services. In any case I can create  PR for the renderToString change (and associated taghelper attribute to enable preboot) or you could opt for the option currently illustrated in the template Angular2Spa template where each framework provides their own prerender code. I like the latter as it makes implementing web workers much easier.

**Comment by SteveSandersonMS** [comment]
Thanks for looking into this.

> or you could opt for the option currently illustrated in the template Angular2Spa template where each framework provides their own prerender code. I like the latter as it makes implementing web workers much easier.

Yes, I agree, and that is the model I'm leaning towards. I'll remove the older `asp-ng2-prerender-module` tag helper in favour of the newer and more flexible `asp-prerender-module` one soon.

So I guess, as per your research, there isn't much we need to do here, as the developer can control their use of preboot by editing the `boot-server.ts` file in whatever way they want.

If you get any insight into what we should do for web workers (if anything) please let me know.

**Comment by jimitndiaye** [comment]
Yea the ```asp-prerender-module``` option is much more flexible. Preboot works with zero modification, do I did modify the ```asp-ng2-prerender-module``` to support preboot anyway.

For workers, as it turns out there isn't much to do there either. You go from having one entry file to multiple (one for the UI thread and the other for the web worker which is loaded asynchoronously). Pre-rendering works as it does now and I was able to get that working.

The only thing I had problems with was using the webpack dev server as there wasn't an obvious way of setting the path to the webpack.config.js file like you can do when setting up the prerendering tag helper. Could just be user error on my part.

To demonstrate web worker support in the template you could do something like i've done [here](https://github.com/jimitndiaye/NodeServices/tree/master/templates/Angular2Spa/ClientApp) (though mine's not finished due to time constraints but the basic idea is there. 

In terms of tooling to support web workers, the only thing I can think of is item templates in VS for bootstrap files.

**Comment by SteveSandersonMS** [comment]
I'm just tidying up some issues and it looks like it would be reasonable to close this one, unless anyone has any specific objections.

The preboot issue is resolved since we migrated to the `asp-prerender-module` helper (you can just pass `preboot: true`).

About web workers, this is also now entirely under the control of the developer since the `asp-prerender-module` approach lets you implement whatever server-side boot code you want. We probably *won't* use web workers in the default Angular2Spa template because it would increase complexity and make it hard to understand for newcomers. Or if anyone thinks it's really important and can be done simply please let me know.
