### ISSUE TITLE
Nuget dependency issue

### ISSUE THREAD

**Issue by oliverguhr** [aspnet/NodeServices#38]
I tryed to use the Microsoft.AspNet.AngularServices Nuget Package. Runnig dnu restore gives me this error:
`Unable to locate Dependency Microsoft.AspNet.NodeServices >= 1.0.0-alpha7`

A quick look at [nuget.org says that the latest version for this package](https://www.nuget.org/packages/Microsoft.AspNet.NodeServices/) is "1.0.0-alpha6"

**Comment by SteveSandersonMS** [comment]
Yes, I delayed publishing the `alpha7` build because I was waiting for us to integrate NodeServices into the common ASP.NET CI and build system. This integration is now done so I'll soon sort out these references.

**Comment by QuinntyneBrown** [comment]
Thank you Mr. Sanderson!

**Comment by eloekset** [comment]
Until the issue is fixed, it seems to work fine to copy these two files locally in the web project and reference 1.0.0-alpha6: https://github.com/aspnet/NodeServices/tree/74cac774f8800f59da9aaf98950b7da9e2297d72/src/Microsoft.AspNet.SpaServices/Routing
But I haven't tested it runtime yet.

**Comment by SteveSandersonMS** [comment]
The current packages are:

 * `Microsoft.AspNetCore.NodeServices` version `1.0.0-beta-000002`
 * `Microsoft.AspNetCore.SpaServices` version `1.0.0-beta-000002`
 * `Microsoft.AspNetCore.AngularServices` version `1.0.0-beta-000002`
 * `Microsoft.AspNetCore.ReactServices` version `1.0.0-beta-000002`

All are published to the public NuGet feed.
