### ISSUE TITLE
Question: will this support spa pre-rendering & pre-fetch with more complex applications?

### ISSUE THREAD

**Issue by andycwk** [aspnet/NodeServices#41]
HI,

It's not clear from the documentation at the moment, so...

Imagin that I'm building an ng2 application that authenticates & uses an api that is on a different sub-domain (api.my-app.com) from the  web client (www.my-app.com - the web client is only responsible for html, js & css - you know the static stuff).

In this example we shall use and store oauth access tokens (including possibly refresh tokens) on the client during the browser session to communicate with the api ..

I know it's still very early days for this package, so... will or how does the angular services help me with this scenario?

Cheers

**Comment by inongogo** [comment]
Correct me if I'm wrong, but I don't think you should rely on the AngularServices for that. I think you should look at [IdentityServer](https://github.com/IdentityServer) or Auth0 for this kind of functionality. They have great samples and a JavaScript library for handling OAuth2 and OpenIdConnect requests to an API endpoint. Also, Brock Allen and Dominick Baier who developed and maintains IdentityServer has som great presentations and blog posts about this kind of security. I recommend you looking at this:
[Dominick Baier Blog](http://leastprivilege.com/)
[Brock Allen Blog](http://brockallen.com/)
[Vimeo Brock Allen](https://vimeo.com/search?q=brock+allen)
[Vimeo Dominick Baier](https://vimeo.com/search?q=Dominick+Baier)

**Comment by andycwk** [comment]
Yeh, thanks for the reply @inongogo but I wasn't asking about how to use AngularServices to authenticate/obtain an access token - that, as you mention, is well managed by the likes of IdentityServer :)

Indeed, re-reading the original question, it may not have been clear what I was asking... I was more interested in how the pre-render & pre-fetch stuff would work with services that are not part of the same web project.. for example micro services or as in the example in the original question... an api on a different endpoint!

Especially when the access token only exists as a javascript object on the web client!

**Comment by pauldotknopf** [comment]
As it stands currently, there doesn't seem to be a way to pre-render data in the templates, whether or not it is provided from inside the application, or from an external source. All data must be fetched on the client.

**Comment by SteveSandersonMS** [comment]
> As it stands currently, there doesn't seem to be a way to pre-render data in the templates

I'm not certain what you mean by that. The server-side code can contain any logic that the client-side code can. Are you referring to the issue that, specifically for the Angular server-side rendering (but not for React), it returns the HTML to the client without waiting for async operations such as data loads? If so, this is an issue in `angular2-universal-preview` that should go away when they have fixed it.

**Comment by pauldotknopf** [comment]
[This](https://github.com/aspnet/NodeServices/blob/b519e58/templates/ReactReduxSpa/Controllers/SampleDataController.cs) WebAPI Controller only serves data up from the client via JavaScript network requests. This data isn't provided by any initial full GET request anywhere, which means you must visit a url (like http://somewhere.com/data), and then the client will load the data with some loading indicator. Instead, the server should be able to provide that data for the initial render, not requiring a client-side network request once the page has loaded.

**Comment by SteveSanderson** [comment]
@pauldotknopf If I'm understanding your requirement correctly, this is accounted for already. See the React+Redux sample for an example where the initial data load is resolved on the server and the client doesn't have to re-fetch it. For Angular 2, you can either use `@Html.PrimeCache`, or as I mentioned the `angular2-universal-preview` module should eventually be fixed to account for waiting for server-side data loads before rendering the HTML. Or is your requirement something different?

**Comment by andycwk** [comment]
Feels like the question has taken on a life of it's own..

.. I simply wanted to know if & how @Html.PrimeCache operates in an environment where the api endpoints are exposed as micro services protected by an access token that is obtained by the web browser (or mobile client) especially if PrimeCache has no idea about the access token!

**Comment by pauldotknopf** [comment]
@andycwk I have an awesome chicken curry soup recipe if you are interested.

**Comment by SteveSandersonMS** [comment]
@andycwk I'm not sure if or how that scenario is compatible with server-side prerendering. If the authentication design is such that only the client is supposed to have access to the token, or goes through some handshake process to acquire it (e.g., including presenting some UI in which the user has to enter a password or similar) then there might not be any relevant way to do that on the server. Ultimately it depends on the exact details of how you've got the auth and token handover set up.

**Comment by SteveSandersonMS** [comment]
@andycwk My expectation for traditional cookie-based auth systems is that PrimeCache would pass through any cookies sent by the browser with the original page request, but that won't help you if your auth setup doesn't involve sending the token to the static UI server.

**Comment by andycwk** [comment]
@SteveSandersonMS yeh, figured as much - just wondered if any one had any smart ideas :(  

So at the moment the static content server needs an auth cookie or something 'else' that can be proxied through to the true endpoint - hmmm, if I have a brain wave I will come back and share (sanity check)!!

But in the meantime, feel welcome to close this question once finished the conversation with @pauldotknopf 

btw @pauldotknopf 'chicken curry soup' sounds great :P

**Comment by SteveSandersonMS** [comment]
Thanks. I'll mark this closed unless anyone has related ongoing questions.
