### ISSUE TITLE
Testing the samples leads to some errors (...uninstalled packages aspnet-prerendering ...)

### ISSUE THREAD

**Issue by CedricDumont** [aspnet/NodeServices#44]
Hello,

I followed the description [Trying the samples](https://github.com/aspnet/NodeServices#using-angularservicesreactservices-in-your-own-projects) more specifically : Using dnx on Windows/Mac/Linux. (on windows 7)

I did all steps: (for the react sample)

```
dnvm use 1.0.0-rc1-final -r coreclr
cd NodeServices
dnu restore
cd /samples/react/ReactGrid
npm install
webpack

```
but encountered some errors on npm packages not installed. I added the two packages below to make it work

```
npm install --save-dev aspnet-prerendering
npm install --save-dev aspnet-webpack
```

It would be best to adapt the packages.config so that others do not encounter the same problem, Or did I do something wrong.

my node version is **5.0.0**
I use  **1.0.0-rc1-update2 clr     x86**

kind regards

**Comment by SteveSandersonMS** [comment]
Thanks for reporting. The package dependencies have been updated and as far as I'm aware should be correct now!
