### ISSUE TITLE
Angular2 server render: Cannot find module 'parse5/index'

### ISSUE THREAD

**Issue by laskoviymishka** [aspnet/NodeServices#55]
Hi all,

I try to add server render to my NG2 app with aspnet core backend and expirience some issues:
``
[Node] root directory: c:\dev\Source\Repos\TaxiExchange.Back\src\TaxiExchange.Back
[Node] Unhandled rejection Error: Cannot find module 'parse5/index'
[Node]     at Function.Module._resolveFilename (module.js:339:15)
[Node]     at Function.Module._load (module.js:290:25)
[Node]     at Module.require (module.js:367:17)
[Node]     at require (internal/module.js:16:19)
[Node]     at Object.<anonymous> (diffing_plugin_wrapper-output_path-jakXnMmL.tmp/angular2/src/platform/server/parse5_adapter.ts:1:14)
[Node]     at Module._compile (module.js:413:34)
[Node]     at Object.Module._extensions..js (module.js:422:10)
[Node]     at Module.load (module.js:357:32)
[Node]     at Function.Module._load (module.js:314:12)
[Node]     at Module.require (module.js:367:17)
[Node]     at require (internal/module.js:16:19)
[Node]     at Object.<anonymous> (c:\dev\Source\Repos\TaxiExchange.Back\src\TaxiExchange.Back\node_modules\angular2-universal\src\node\node.ts:2:1)
[Node]     at Module._compile (module.js:413:34)
[Node]     at Object.Module._extensions..js (module.js:422:10)
[Node]     at Module.load (module.js:357:32)
[Node]     at Function.Module._load (module.js:314:12)
[Node]     at Module.require (module.js:367:17)
[Node]     at require (internal/module.js:16:19)
[Node]     at Object.<anonymous> (c:\dev\Source\Repos\TaxiExchange.Back\src\TaxiExchange.Back\node_modules\angular2-universal\src\node\index.ts:1:22)
[Node]     at Module._compile (module.js:413:34)
[Node]     at Object.Module._extensions..js (module.js:422:10)
[Node]     at Module.load (module.js:357:32)
``
My server-boot.ts pretty much same as template.
Could any please advise with this.

**Comment by laskoviymishka** [comment]
According to __https://github.com/angular/angular/issues/7081__ this is known issue, and could be fixed by adding specific version of parse5 as dependencie.

**Comment by SteveSandersonMS** [comment]
Do you have any repro steps for this? When I run the samples in the repo, or the output from `yo aspnet-spa`, I don't get this error.

I'm totally happy to take your pull request #58 but would prefer to be sure I understand where the problem occurs first if that's OK.

**Comment by laskoviymishka** [comment]
The problem with npm resolution for parse5 for some of child modules (it mark as latest which is not accurate), you may fix it with _https://github.com/aspnet/NodeServices/commit/5e92ec0bee9ae4db48bd20b456c9701382c31d9d_ commit.
Not sure how, but now it not reproducing :sweat:
