### ISSUE TITLE
Webpack default entry issue: webpackConfig.entry.main.unshift is not a function.

### ISSUE THREAD

**Issue by laskoviymishka** [aspnet/NodeServices#56]
There is a statement inside of webpack dev middleware ts:
`webpackConfig.entry['main'].unshift('webpack-hot-middleware/client');`

Beside assuming that we have default main entry (which is not really good, but there is already TODO here), this allso assume that entry point is an array. Webpack is allow to you have this entry as a string. 
Webpack ng2 starter as example have following config:
`entry: {
    'polyfills': './src/polyfills.ts',
    'vendor': './src/vendor.ts',
    'main': './src/main.browser.ts'
  },`
In this scenario you will have error:
webpackConfig.entry.main.unshift is not a function.

**Comment by vladoros** [comment]
Has this fix been released?

**Comment by laskoviymishka** [comment]
I think so, do you face this issue?

**Comment by vladoros** [comment]
Yes, I cleaned up node_modules & typings seems like there was an issue with the module I was integrating with (ng2-admin).
Thanks.

**Comment by laskoviymishka** [comment]
Can you please file separate issue with whole stack trace, and your we pack configs

**Comment by camtotheron** [comment]
I am still encountering this error with webpack-dev-server version 1.14.1

TypeError: config.entry.unshift is not a function
at Object.<anonymous> (D:\repos\teamplus-calendar\server.js:11:14)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.runMain (module.js:575:10)
    at run (bootstrap_node.js:352:7)
    at startup (bootstrap_node.js:144:9)
    at bootstrap_node.js:467:3
