### ISSUE TITLE
Can not activate specified DNX runtime for Mac

### ISSUE THREAD

**Issue by sirockin** [aspnet/NodeServices#61]
When I try to activate the runtime specified in the [blogpost](http://blog.stevensanderson.com/2016/05/02/angular2-react-knockout-apps-on-aspnet-core/)  having installed asp.net from the [specified ling](http://blog.stevensanderson.com/2016/05/02/angular2-react-knockout-apps-on-aspnet-core/) I get the following results:

`Davids-MacBook-Pro-6:~ sirockin$ dnvm use 1.0.0-rc1-final -r coreclr
Cannot find dnx-coreclr-darwin-x64.1.0.0-rc1-final, do you need to run 'dnvm install 1.0.0-rc1-final'?
Davids-MacBook-Pro-6:~ sirockin$ dnvm list

Active Version              Runtime Architecture OperatingSystem Alias
------ -------              ------- ------------ --------------- -----
       1.0.0-rc1-final      mono                 linux/osx       
       1.0.0-rc1-update1    mono                 linux/osx       
  *    1.0.0-rc1-update1    coreclr x64          darwin          default
       1.0.0-rc1-update1    mono                 linux/osx       

Davids-MacBook-Pro-6:~ sirockin$ dnvm install 1.0.0-rc1-final
dnx-mono.1.0.0-rc1-final already installed in /Users/sirockin/.dnx
Adding /Users/sirockin/.dnx/runtimes/dnx-mono.1.0.0-rc1-final/bin to process PATH
Davids-MacBook-Pro-6:~ sirockin$ dnvm use 1.0.0-rc1-final -r coreclr
Cannot find dnx-coreclr-darwin-x64.1.0.0-rc1-final, do you need to run 'dnvm install 1.0.0-rc1-final'?
Davids-MacBook-Pro-6:~ sirockin$`

**Comment by SteveSandersonMS** [comment]
If you want to use `1.0.0-rc1-final` on the `coreclr` runtime then you might need to install it as follows:

    dnvm install 1.0.0-rc1-final -r coreclr

It looks like just running `dnvm install 1.0.0-rc1-final` on its own won't install it for `coreclr` if you have already installed it for `mono`.

Alternatively you can move to update 2 (run `dnvm upgrade -r coreclr`) and then `dnvm use 1.0.0-rc1-update2 -r coreclr`.

I'll tweak the instructions in the blog post to account for people having different versions installed.
