### ISSUE TITLE
Angular2 rc1 upgrade

### ISSUE THREAD

**Issue by laskoviymishka** [aspnet/NodeServices#62]
Angular team have published first release candidate. We should upgrade template for it (and may be music store sample, but this part could be real pain).

**Comment by laskoviymishka** [comment]
This is blocked till PR _https://github.com/angular/universal/pull/381_ closed.

**Comment by laskoviymishka** [comment]
ng2 universal was updated to rc1, so it now not blocked anymore

**Comment by SteveSandersonMS** [comment]
Thanks for the PR - merged!

**Comment by SteveSandersonMS** [comment]
And yes, will get to the Music Store sample later, but it's not such a high priority.
