### ISSUE TITLE
User authentication

### ISSUE THREAD

**Issue by Raika** [aspnet/NodeServices#65]
Is there any solution for handling user authentication in both server side and client side?

**Comment by laskoviymishka** [comment]
Cookies auth should work properly

**Comment by Raika** [comment]
In a react template I'm saving a cookie with `react-cookie` but in the first request to server, no cookie was sent. 
And for `Web API` request I had to add `credentials: 'same-origin'` to fetch options for sending cookies.
Did I do something wrong?

**Comment by laskoviymishka** [comment]
@Raika looks like there is some issue, i'll try to create sample and figure out what goes wrong

**Comment by laskoviymishka** [comment]
Well there is no cookies pushing to inner node web app, you could try to use different node hosting model.
`

            services.AddNodeServices(new NodeServicesOptions
            {
                HostingModel = NodeHostingModel.InputOutputStream
            });
`
You could try add following lines of code to startup.

**Comment by laskoviymishka** [comment]
Does it helped?
